wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
architecture:
  desc: null
  value: null
dataset:
  desc: null
  value: KSUEmotions
epochs:
  desc: null
  value: 40
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707473558.723899
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.9.13
      5: 0.16.2
      6: 4.37.2
      8:
      - 5
      13: darwin-x86_64
